const people = [
  {
    id: "person-0",
    regexName: /(?:Annegret )?Kramp[ -]Karrenbauer/gi,
    regexAbbrev: /\bAKK\b(?![ -]47)/gi,
    substitutionsFirst: [
      "Aalgerät",
      "Abendbrot",
      "Abfluggate",
      "Abgeweht",
      "Abhörgerät",
      "Affenzeh",
      "Aggressiv",
      "Akazienfleck",
      "Aknecreme",
      "Algensee",
      "Allesgeht",
      "Alleskleb",
      "Allesweg",
      "Alter Met",
      "Altgewebt",
      "Ammenschreck",
      "Ammoniak",
      "Ampelgrät",
      "Ampferbeet",
      "Ananasbeet",
      "Angedreht",
      "Angedreht",
      "Angelgrät",
      "Angerät",
      "Angriffskrieg",
      "Ankerbett",
      "Annegate",
      "Annegret",
      "Annektiert",
      "Annregret",
      "Apfelmet",
      "Apfeltee",
      "Arbeitsamt",
      "Armeegebet",
      "Armgedreht",
      "Arschgeweih",
      "Assizeh",
      "Astverdreht",
      "Atemgerät",
      "Aufgedreht",
      "Ausgelebt",
      "Ballergret",
      "Bannegret",
      "Pannengerät",
      "Pansensalat",
      "Panzergret",
      "Stoßgebet",
      "Un-Fair Trade",
      "Undefined",
      "Windgedreht",
      "Windverweht",
    ],
    substitutionsMiddle: [
      "Band",
      "Ganz",
      "Hanf",
      "Harz",
      "Kampf",
      "Kann",
      "Kant",
      "Katz",
      "Kein",
      "Kennt",
      "Klamm",
      "Klang",
      "Klein",
      "Klotz",
      "Klump",
      "Kommt",
      "Kotz",
      "Krabbe",
      "Kramp",
      "Krampf",
      "Kran",
      "Krank",
      "Kranz",
      "Krebs",
      "Krupp",
      "Land",
      "Lanz",
      "Mampf",
      "Pfand",
      "Pflanz",
      "Punk",
      "Rang",
      "Sand",
      "Schrank",
      "Tand",
      "Tank",
      "Trump",
      "Trumpf",
      "Wand",
    ],
    substitutionsLast: [
      //combined lastnames now need a dash upfront
      "-Akkuschrauber",
      "-Flaschenknauser",
      "-Gartenlaube",
      "-Gassenhauer",
      "-Harkenklauber",
      "-Haubentaucher",
      "-Kackebauer",
      "-Kackenkarrer",
      "-Kalterschauer",
      "-Kamelraucher",
      "-Kamillenbrauer",
      "-Kampfhubschrauber",
      "-Kapillarenkalker",
      "-Karatehauer",
      "-Kardinalvertrauer",
      "-Karottenbauer",
      "-Karpfenkauer",
      "-Karrenbauer",
      "-Karrenklauer",
      "-Kastratenkrauler",
      "-Katerflauer",
      "-Katzenjammer",
      "-Katzenkrauler",
      "-Katzenmiauer",
      "-Keilerhauer",
      "-Klammerkauer",
      "-Klausverhauer",
      "-Klimperpower",
      "-Kliniktrauer",
      "-Kloakenrauer",
      "-Klosteinmauer",
      "-Knarrenbauer",
      "-Knotentauer",
      "-Koksanbauer",
      "-Kolabrauer",
      "-Kolibriklabauter",
      "-Konradadenauer",
      "-Koreamauer",
      "-Krakenkrauler",
      "-Kranbauer",
      "-Kreisbegatter",
      "-Krillverdauer",
      "-Krimkalauer",
      "-Kroatenlauer",
      "-Nasenklauer",
      "-Nervenklauer",
      "-Neunmalschlauer",
      "-Pfaffenhauer",
      "-Pfarrerklauer",
      "-Schinkenklauber",
      "-Schnakenfauna",
      "-Wackelbauchtier",
      "-Wannentaucher",
      "-Winterpflaume",
    ],
    substitutionsComplete: [
      "AKK-47",
      "Büchsengretl",
      "CDUzi",
      "Granaten-Gretel",
      "Knarren-Greta",
    ],
  },
  {
    id: "person-1",
    regexName: /(?:Olaf )?Scholz/gi,
    regexAbbrev: null,
    substitutionsFirst: ["Olaf"],
    substitutionsMiddle: [" "],
    substitutionsLast: ["Schulz"],
    substitutionsComplete: ["Giro Olaf", "Wumms-Olaf"],
  },
  {
    id: "person-2",
    regexName: /(?:Andreas |Andi |Andy )?[S]{1}cheuer/gi,
    regexAbbrev: null,
    substitutionsFirst: ["Andi"],
    substitutionsMiddle: [" "],
    substitutionsLast: ["Bescheuert", "B. Scheuert"],
    substitutionsComplete: ["Roller-Andi"],
  },
  {
    id: "person-3",
    regexName: /(?:Julia )?Klöckner/gi,
    regexAbbrev: null,
    substitutionsFirst: ["Julia"],
    substitutionsMiddle: [" "],
    substitutionsLast: [" von Nestlé"],
    substitutionsComplete: ["Die Weinkönigin"],
  },
  {
    id: "person-4",
    regexName: /(?:Armin )?Laschet/gi,
    regexAbbrev: null,
    substitutionsFirst: ["Achim"],
    substitutionsMiddle: [" "],
    substitutionsLast: ["Laschet", "Lachet"],
    substitutionsComplete: ["Würfel-Armin"],
  },
  {
    id: "person-5",
    regexName: /(?:Annalena )?Baerbock/gi,
    regexAbbrev: null,
    substitutionsFirst: ["Annalena"],
    substitutionsMiddle: [" "],
    substitutionsLast: ["Bärbaum"],
    substitutionsComplete: ["Die Annalena"],
  },
  {
    id: "person-6",
    regexName: /(?:Angela )?Merkel/gi,
    regexAbbrev: null,
    substitutionsFirst: ["Angola"],
    substitutionsMiddle: [" "],
    substitutionsLast: ["Merkel"],
    substitutionsComplete: ["Mutti"],
  },
  {
    regexName: /(?:Björn )?Höcke/gi,
    regexAbbrev: null,
    substitutionsFirst: ["Bernd"],
    substitutionsMiddle: [" "],
    substitutionsLast: ["Höcke"],
    substitutionsComplete: ["AfD-Onkel"],
  },
];
